# Generated by Django 5.0.6 on 2024-06-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('receita', models.TextField(max_length=225)),
                ('gasto', models.FloatField()),
            ],
        ),
    ]
